server {
    listen 80;
    server_name localhost;
    # Redireciona tudo para HTTPS para forçar o uso do HTTP/2
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on; # Habilita HTTP/2
    server_name localhost;

    # Certificados gerados pelo Dockerfile
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # ⚠️ RESOLUÇÃO DE PROBLEMAS SSE ⚠️
        # Desliga o buffer do Nginx para requisições FastCGI (PHP)
        fastcgi_buffering off;
        fastcgi_cache off;

        # Aumenta o timeout para evitar que o Nginx derrube a conexão ociosa (1 hora)
        fastcgi_read_timeout 3600;
    }
}